//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMove.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayudantes.
        /// </summary>
        public static string ayudantes {
            get {
                return ResourceManager.GetString("ayudantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Simple Move podrás encontrar la persona indicada para ti, para que te ayude con tus mudanzas.
        /// </summary>
        public static string ayudantesTexto {
            get {
                return ResourceManager.GetString("ayudantesTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vamos.
        /// </summary>
        public static string BotonIndex {
            get {
                return ResourceManager.GetString("BotonIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificame.
        /// </summary>
        public static string BotonNotificame {
            get {
                return ResourceManager.GetString("BotonNotificame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductores.
        /// </summary>
        public static string conductores {
            get {
                return ResourceManager.GetString("conductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Simple Move podras encontrar el mejor conductor indicada para ti, para que te ayude con tus mudanzas.
        /// </summary>
        public static string ConductoresTexto {
            get {
                return ResourceManager.GetString("ConductoresTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conocenos.
        /// </summary>
        public static string ConocenosIndex {
            get {
                return ResourceManager.GetString("ConocenosIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nos enfocamos en tu seguridad al momento de realizar mudanzas.
        /// </summary>
        public static string DescripciónIndex {
            get {
                return ResourceManager.GetString("DescripciónIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactanos.
        /// </summary>
        public static string LayoutContactanos {
            get {
                return ResourceManager.GetString("LayoutContactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string LayoutInformacion {
            get {
                return ResourceManager.GetString("LayoutInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string LayoutServicios {
            get {
                return ResourceManager.GetString("LayoutServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple Move llego para ser la solución de muchas personas que no saben a quien recurrir cuando de una mudanza se trata, con Simple Move puedes contactar con personas que esten enteradas del asunto de mudanzas.
        /// </summary>
        public static string SimpleMoveText {
            get {
                return ResourceManager.GetString("SimpleMoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscríbete para recibir notificaciones.
        /// </summary>
        public static string Suscribete {
            get {
                return ResourceManager.GetString("Suscribete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Somos una plataforma de información, donde podrás encontrar gente dispuesta a ayudarte con tus mudanzas, desde conductores experimentados, hasta ayudantes experimentados y lo MEJOR a un costo razonable.
        /// </summary>
        public static string TextoConocenosIndex {
            get {
                return ResourceManager.GetString("TextoConocenosIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
    }
}
